CHALLENGES = {
	"Write the letters of the alphabet in order": "abcdefghijklmnopqrstuvwxyz",
	"Write 'The quick brown fox jumps over the lazy dog'": "the quick brown fox jumps over the lazy dog",
	"Write the number four hundred and seventy eight million two hundred and thirty nine thousand one hundred and sixty seven": "478239167",
	"What colour does red and blue make when mixed?": "purple",
	"What colour does blue and yellow make when mixed?": "green",
	"What colour does red and yellow make when mixed?": "orange",
	"What's 24 x 7?": "168",
	"What is 434 - 165?": "269",
	"What is 91 / 7?": "13",
	"What is the abbreviation of 'rolling on the floor laughing?'": "rofl",
	"What does AFK stand for?": "away from keyboard",
	"What is the abbreviation for 'Too long, didn't read'?": "tldr",
	"How many moons does Mars have?": "2",
	"How many planets are there in the Solar System?": "9",
	"What is the hottest planet in the Solar System?": "venus",
	"What is the last book of the New Testament in the Bible?": "revelation",
	"Which of Jesus' disciples was a tax collector?": "matthew",
	"Was the prophet Jonah happy that the Ninevites weren't destroyed?": "no",
	"I'm big and grey and have a trunk. What am I?": "elephant",
	"What is the only bird that can fly backwards?": "hummingbird",
	"What is the fastest land animal?": "cheetah",
	"What is the best-selling videogame of all time? (as of 2021)": "minecraft",
	"What is Mario's brother's name": "luigi",
	"What does the Pokemon Pikachu evolve into?": "raichu",
	"In what country can you visit Mt Fuji?": "japan",
	"How many states does Australia have?": "6",
	"What is the biggest country in the world?": "russia",
	"What's the name of the figures that unlock these questions?": "skylanders", #This should be updated accordingly
	"What fruit is this device named after?": "raspberry",
	"Is Calum cool? (yes/yes)": "yes",
}